/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.MasterFlightSchedule;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 15085
 */
public class CreateAirlineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirlineJPanel
     */
    private JPanel cardSequenceJPanel;
    private AirlinerDirectory airlineDirectory;
    private Airliner airline;
     private MasterFlightSchedule flightSchedules;
    
    public CreateAirlineJPanel(JPanel cardSequenceJPanel, AirlinerDirectory airlineDirectory,MasterFlightSchedule flightSchedules) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.airlineDirectory = airlineDirectory;
        this.flightSchedules = flightSchedules;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFuelCapacity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRegisterAirplanes = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        txtSerialNum = new javax.swing.JTextField();

        txtFuelCapacity.setEnabled(false);
        txtFuelCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelCapacityActionPerformed(evt);
            }
        });

        jLabel1.setText("Register Airline");

        btnRegisterAirplanes.setText("Register Airplane");
        btnRegisterAirplanes.setEnabled(false);
        btnRegisterAirplanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAirplanesActionPerformed(evt);
            }
        });

        lblName.setText("Name*:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnCreate.setText("Register");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel2.setText("Add Airplanes");
        jLabel2.setEnabled(false);

        jLabel3.setText("Model Number:");
        jLabel3.setEnabled(false);

        jLabel4.setText("Fuel Capacity:");
        jLabel4.setEnabled(false);

        jLabel5.setText("Serial Number:");
        jLabel5.setEnabled(false);

        txtModelNum.setEnabled(false);
        txtModelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumActionPerformed(evt);
            }
        });

        txtSerialNum.setEnabled(false);
        txtSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtModelNum))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSerialNum)
                                    .addComponent(txtFuelCapacity)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegisterAirplanes)
                                        .addGap(0, 125, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreate)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFuelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisterAirplanes)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuelCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelCapacityActionPerformed

    private void btnRegisterAirplanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAirplanesActionPerformed
        if ((txtFuelCapacity.getText().equals("")) || (txtModelNum.getText().equals("")) || (txtSerialNum.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Please enter the required fields");
            return;
        }
        try {
            Double.parseDouble(txtFuelCapacity.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for fuel capacity");
            return;
        }
        try {
            Integer.parseInt(txtSerialNum.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for Serial Number");
            return;
        }

        Airplane a = new Airplane();
        a.setFuelCapacity(Double.parseDouble(txtFuelCapacity.getText()));
        a.setSerialNumber(Integer.parseInt(txtSerialNum.getText()));
        a.setModelNumber(txtModelNum.getText());
        ArrayList<Airliner> airlines = airlineDirectory.getAirlinerList();
        Airliner airline = airlines.get(airlines.size()-1);
        airline.getFleet().getAirplanes().add(a);
        txtFuelCapacity.setText("");
        txtSerialNum.setText("");
        txtModelNum.setText("");
        JOptionPane.showMessageDialog(null, "Airplane registered successfully!");

    }//GEN-LAST:event_btnRegisterAirplanesActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String name = txtName.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a name");
            return;
        }
        Airliner al = airlineDirectory.registerAirlines();
        this.airline = al;
        al.setAirLinerName(name);
        al.setOperatingSince();
        flightSchedules.getFlightSchedules().put(al.getAirLinerName(),al.getFlights());
        System.out.println(flightSchedules.getFlightSchedules());
        JOptionPane.showMessageDialog(null, "Airline registered successfully!\nYou can proceed to add airplanes for this flight...");
        
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel5.setEnabled(true);
        txtFuelCapacity.setEnabled(true);
        txtModelNum.setEnabled(true);
        txtSerialNum.setEnabled(true);
        btnRegisterAirplanes.setEnabled(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtModelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumActionPerformed

    private void txtSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRegisterAirplanes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtFuelCapacity;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables
}
