/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.Airplane;
import Business.Flight;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 15085
 */
public class CreateFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFlightJPanel
     */
    private JPanel cardSequenceJPanel;
    private Airliner al;
    public CreateFlightJPanel(JPanel cardSequenceJPanel, Airliner al) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.al = al;
        comboBoxFlights.removeAllItems();
        comboBoxFlights.addItem("--Select--");
        for(Airplane a : al.getFleet().getAirplanes()) {
            comboBoxFlights.addItem(a.getModelNumber());
        }
        labelHeading.setText("Create a " + al.getAirLinerName() + " Flight");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfieldArrivalCity = new javax.swing.JTextField();
        textfieldDepartureCity = new javax.swing.JTextField();
        btnAddFlight = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelHeading = new javax.swing.JLabel();
        comboBoxFlights = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textfieldFlightTime = new javax.swing.JTextField();

        textfieldArrivalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldArrivalCityActionPerformed(evt);
            }
        });

        textfieldDepartureCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDepartureCityActionPerformed(evt);
            }
        });

        btnAddFlight.setText("Add Flight");
        btnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Airplane Name:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("From City:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("To City:");

        labelHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeading.setText("Add a ****  Flight");

        comboBoxFlights.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFlightsActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Departure Time:");

        textfieldFlightTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldFlightTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboBoxFlights, 0, 143, Short.MAX_VALUE)
                            .addComponent(textfieldFlightTime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddFlight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldDepartureCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldArrivalCity, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 311, Short.MAX_VALUE))
                    .addComponent(labelHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textfieldDepartureCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textfieldArrivalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textfieldFlightTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddFlight)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldArrivalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldArrivalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldArrivalCityActionPerformed

    private void textfieldDepartureCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDepartureCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDepartureCityActionPerformed

    private void btnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightActionPerformed
        String modelno = (String) comboBoxFlights.getSelectedItem();
        if(modelno.equalsIgnoreCase("--Select--")) {
            JOptionPane.showMessageDialog(null, "Please select an airplane!");
            return;
        }
        else{
            Flight f = new Flight();
            f.setArrivalCity(textfieldArrivalCity.getText());
            f.setDepartureCity(textfieldDepartureCity.getText());
            f.setTime(textfieldFlightTime.getText());

            Airplane airplane = al.getFleet().findAirplaneByModelNumber(modelno);
            f.setAirplane(airplane);
            al.getFlights().getFlights().add(f);

            JOptionPane.showMessageDialog(null, "Flight created successfully for " + modelno);
        }
    
    }//GEN-LAST:event_btnAddFlightActionPerformed

    private void comboBoxFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFlightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxFlightsActionPerformed

    private void textfieldFlightTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldFlightTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldFlightTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlight;
    private javax.swing.JComboBox<String> comboBoxFlights;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JTextField textfieldArrivalCity;
    private javax.swing.JTextField textfieldDepartureCity;
    private javax.swing.JTextField textfieldFlightTime;
    // End of variables declaration//GEN-END:variables
}
