/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer;
import Business.CustomerDirectory;
import Business.Flight;
import Business.MasterFlightSchedule;
import Business.Ticket;
import Business.TicketHistory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BookingHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingHistoryJPanel
     */
    private JPanel cardSequenceJPanel;
    private MasterFlightSchedule flightSchedules;
    private Customer customer;
    private TicketHistory bookingHistory;

    public BookingHistoryJPanel(JPanel cardSequenceJPanel, CustomerDirectory customerDirectory, MasterFlightSchedule flightSchedules, TicketHistory bookingHistory) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.customer = customer;
        this.flightSchedules = flightSchedules;
        this.bookingHistory = bookingHistory;
        populateHistory();
    }

    public void populateHistory() {
        DefaultTableModel dtm = (DefaultTableModel) tblBookingHistory.getModel();
        dtm.setRowCount(0);
        for (Ticket ticket : bookingHistory.getBookingHistory()) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = ticket;
            row[1] = ticket.getCustomer().getContactNumber();
            row[2] = ticket.getFlight();
            row[3] = ticket.getFlight().getDepartureCity();
            row[4] = ticket.getFlight().getArrivalCity();
            row[5] = ticket.getSeatNumber();
            row[6] = ticket.getFlight().getPrice();
            row[7] = ticket.getFlight().getAirlineName();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookingHistory = new javax.swing.JTable();
        cancelBookingBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        jScrollPane1.setBackground(null);

        tblBookingHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust. Name", "Contact Number", "Model Number", "Departure", "Destination", "Seat number", "Price", "Airline Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBookingHistory);

        cancelBookingBtn.setBackground(null);
        cancelBookingBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cancelBookingBtn.setText("Cancel Booking");
        cancelBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(null);
        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Search by customer name:");

        searchField.setBackground(null);
        searchField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        searchBtn.setBackground(null);
        searchBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(null);
        clearBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking History");

        backBtn.setBackground(null);
        backBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        backBtn.setText("< Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 355, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBookingHistory.getSelectedRow();
        if (selectedRow >= 0) {
            int input = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel this booking?");
            if (input == 0) {
                Ticket t = (Ticket) tblBookingHistory.getValueAt(selectedRow, 0);
                bookingHistory.getBookingHistory().remove(t);

                Flight f = (Flight) tblBookingHistory.getValueAt(selectedRow, 2);
                String seatNumber = (String)tblBookingHistory.getValueAt(selectedRow, 5);
                f.getSeat().getSeatNumber().replace(seatNumber,0,1);
                populateHistory();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a ticket to proceed.");
            return;
        }

    }//GEN-LAST:event_cancelBookingBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String search = searchField.getText();
        DefaultTableModel dtm = (DefaultTableModel) tblBookingHistory.getModel();
        dtm.setRowCount(0);
        for (Ticket ticket : bookingHistory.getBookingHistory()) {
            if (ticket.getCustomer().getName().equalsIgnoreCase(search)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = ticket.getCustomer().getName();
                row[1] = ticket.getCustomer().getContactNumber();
                row[2] = ticket.getFlight();
                row[3] = ticket.getFlight().getDepartureCity();
                row[4] = ticket.getFlight().getArrivalCity();
                row[5] = ticket.getSeatNumber();
                row[6] = ticket.getFlight().getPrice();
                row[7] = ticket.getFlight().getAirlineName();
                dtm.addRow(row);
            }
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        searchField.setText("");
        populateHistory();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelBookingBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable tblBookingHistory;
    // End of variables declaration//GEN-END:variables
}
