/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.Airplane;
import Business.Flight;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 15085
 */
public class CreateFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFlightJPanel
     */
    private JPanel cardSequenceJPanel;
    private Airliner al;
    public CreateFlightJPanel(JPanel cardSequenceJPanel, Airliner al) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.al = al;
        comboBoxFlights.removeAllItems();
        comboBoxFlights.addItem("--Select--");
        for(Airplane a : al.getFleet().getAirplanes()) {
            comboBoxFlights.addItem(a.getModelNumber());
        }
        labelHeading.setText("Create " + al.getAirLinerName() + " Flight");
    }
    
    private boolean DatePatternCorrect() {
       Pattern p = Pattern.compile("^[*\\d]+/[*\\d]+/[*\\d]+$");
       Matcher m = p.matcher(textfieldFlightDate.getText());
       boolean b = m.matches();
       return b;
   }
    
    private boolean DepartTimePatternCorrect() {
       Pattern p = Pattern.compile("^[*\\d]+:[*\\d]+$");
       Matcher m = p.matcher(textfieldDepartTime.getText());
       boolean b = m.matches();
       return b;
   }
    
    private boolean ArrivalTimePatternCorrect() {
       Pattern p = Pattern.compile("^[*\\d]+:[*\\d]+$");
       Matcher m = p.matcher(textfieldArrivalTime.getText());
       boolean b = m.matches();
       return b;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddFlight = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelHeading = new javax.swing.JLabel();
        comboBoxFlights = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        textfieldDepartTime = new javax.swing.JTextField();
        textfieldFlightDate = new javax.swing.JTextField();
        textfieldArrivalCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textfieldDepartureCity = new javax.swing.JTextField();
        textfieldArrivalTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textfieldPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddFlight.setBackground(new java.awt.Color(255, 255, 255));
        btnAddFlight.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnAddFlight.setText("Add Flight");
        btnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Airplane Name:");

        labelHeading.setBackground(new java.awt.Color(255, 255, 255));
        labelHeading.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeading.setText("Add a ****  Flight");

        comboBoxFlights.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxFlights.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFlightsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Departure Time:");

        textfieldDepartTime.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldDepartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDepartTimeActionPerformed(evt);
            }
        });

        textfieldFlightDate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldFlightDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldFlightDateActionPerformed(evt);
            }
        });

        textfieldArrivalCity.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldArrivalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldArrivalCityActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Flight Date:");

        textfieldDepartureCity.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldDepartureCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDepartureCityActionPerformed(evt);
            }
        });

        textfieldArrivalTime.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldArrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldArrivalTimeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Arrival Time:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("From City:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("To City:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Price:");

        textfieldPrice.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPriceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("USD");

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        backBtn.setText("< Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(comboBoxFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textfieldFlightDate)
                                    .addComponent(textfieldArrivalTime)
                                    .addComponent(textfieldDepartTime)
                                    .addComponent(textfieldDepartureCity)
                                    .addComponent(textfieldArrivalCity)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textfieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(107, 733, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textfieldFlightDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textfieldDepartureCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textfieldArrivalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textfieldDepartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textfieldArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textfieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightActionPerformed
        String modelno = (String) comboBoxFlights.getSelectedItem();
        if(textfieldFlightDate.getText().equals("") ||
           textfieldArrivalCity.getText().equals("") || 
           textfieldDepartureCity.getText().equals("") ||
           textfieldDepartTime.getText().equals("") || 
           textfieldArrivalTime.getText().equals("")|| 
           textfieldPrice.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter all the fields!");
            return;
        }
        if(modelno.equalsIgnoreCase("--Select--")) {
            JOptionPane.showMessageDialog(null, "Please select an airplane!");
            return;
        }
        
        if(!DatePatternCorrect() || textfieldFlightDate.getText().length()!=10) {
            JOptionPane.showMessageDialog(null, "Please enter Date in MM-DD-YYYY format");
            return;
        }
        
        if(!DepartTimePatternCorrect() || textfieldDepartTime.getText().length()!=5) {
            JOptionPane.showMessageDialog(null, "Please enter Departure Time in HH:MM format");
            return;
        }
        
        if(!ArrivalTimePatternCorrect() || textfieldArrivalTime.getText().length()!=5) {
            JOptionPane.showMessageDialog(null, "Please enter Arrival Time in HH:MM format");
            return;
        }
        
        
            Flight f = new Flight();
            f.setFlyDate(textfieldFlightDate.getText());
            f.setArrivalCity(textfieldArrivalCity.getText());
            f.setDepartureCity(textfieldDepartureCity.getText());
            f.setDeparturetime(textfieldDepartTime.getText());
            f.setArrivaltime(textfieldArrivalTime.getText());
            f.setAirlineName(al.getAirLinerName());
            Airplane airplane = al.getFleet().findAirplaneByModelNumber(modelno);
            f.setPrice(Double.parseDouble(textfieldPrice.getText()));
            f.setAirplane(airplane);
            al.getFlights().getFlights().add(f);

            JOptionPane.showMessageDialog(null, "Flight created successfully for " + modelno);
        
    
    }//GEN-LAST:event_btnAddFlightActionPerformed

    private void comboBoxFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFlightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxFlightsActionPerformed

    private void textfieldDepartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDepartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDepartTimeActionPerformed

    private void textfieldFlightDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldFlightDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldFlightDateActionPerformed

    private void textfieldArrivalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldArrivalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldArrivalCityActionPerformed

    private void textfieldDepartureCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDepartureCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDepartureCityActionPerformed

    private void textfieldArrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldArrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldArrivalTimeActionPerformed

    private void textfieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPriceActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnAddFlight;
    private javax.swing.JComboBox<String> comboBoxFlights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JTextField textfieldArrivalCity;
    private javax.swing.JTextField textfieldArrivalTime;
    private javax.swing.JTextField textfieldDepartTime;
    private javax.swing.JTextField textfieldDepartureCity;
    private javax.swing.JTextField textfieldFlightDate;
    private javax.swing.JTextField textfieldPrice;
    // End of variables declaration//GEN-END:variables
}
