/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.MasterFlightSchedule;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15085
 */
public class ManageAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinerPanel
     */
    private JPanel cardSequenceJPanel;
    private AirlinerDirectory airlineDirectory;
    private MasterFlightSchedule flightSchedules;
    public ManageAirlinerJPanel(JPanel cardSequenceJPanel,AirlinerDirectory airlineDirectory,MasterFlightSchedule flightSchedules) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.airlineDirectory = airlineDirectory;
        this.flightSchedules = flightSchedules;
        populateTable(this.airlineDirectory.getAirlinerList());
    }
    
    public void populateTable(ArrayList<Airliner> airlines){
        DefaultTableModel dtm = (DefaultTableModel) tblAirlines.getModel();
        dtm.setRowCount(0);
        for(Airliner al : airlines){
            Object row[]= new Object[3];
            row[0] = al;
            row[1] = al.getFleet().getAirplanes().size();
            row[2]=al.getFlights().getFlights().size();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageFlights = new javax.swing.JButton();
        btnViewAirline = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirlines = new javax.swing.JTable();
        btnCreateAirliner = new javax.swing.JButton();
        btnDeleteAirline = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        btnRefreshAirlines = new javax.swing.JButton();

        btnManageFlights.setBackground(new java.awt.Color(255, 255, 255));
        btnManageFlights.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnManageFlights.setText("Manage Flights");
        btnManageFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightsActionPerformed(evt);
            }
        });

        btnViewAirline.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAirline.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnViewAirline.setText("View Airliner");
        btnViewAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlineActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Airliners");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblAirlines.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblAirlines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "No of airplanes", "Flights Scheduled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAirlines.setRowHeight(25);
        jScrollPane1.setViewportView(tblAirlines);

        btnCreateAirliner.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAirliner.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnCreateAirliner.setText("Add New Airliner");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        btnDeleteAirline.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAirline.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnDeleteAirline.setText("Delete Airliner");
        btnDeleteAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirlineActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        backBtn.setText("< Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnRefreshAirlines.setBackground(new java.awt.Color(255, 255, 255));
        btnRefreshAirlines.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnRefreshAirlines.setText("Refresh");
        btnRefreshAirlines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAirlinesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshAirlines, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(btnManageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshAirlines, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAirlines.getSelectedRow();
        if(selectedRow<0) {
            JOptionPane.showMessageDialog(null, "Please select an Airline first");
            return;
        }

        else
        {
            Airliner al = (Airliner)tblAirlines.getValueAt(selectedRow, 0);
            ManageFlightsJPanel panel = new ManageFlightsJPanel(cardSequenceJPanel,al);
            CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
            cardSequenceJPanel.add("ManageFlightsJPanel",panel);
            layout.next(cardSequenceJPanel);
        }

    }//GEN-LAST:event_btnManageFlightsActionPerformed

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // Create An Airline
        CreateAirlineJPanel createAirlineJPanel = new CreateAirlineJPanel(cardSequenceJPanel,airlineDirectory,flightSchedules);
        CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
        cardSequenceJPanel.add("CreateAirlines",createAirlineJPanel);
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnViewAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlineActionPerformed
        int selectedRow = tblAirlines.getSelectedRow();
        if(selectedRow>=0){
              Airliner airline= (Airliner)tblAirlines.getValueAt(selectedRow, 0);
              ViewAirlineJPanel viewJPanel = new ViewAirlineJPanel(cardSequenceJPanel,airline,airlineDirectory,flightSchedules);
              cardSequenceJPanel.add("ViewJPanel",viewJPanel);
              CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
              layout.next(cardSequenceJPanel);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view Details!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewAirlineActionPerformed

    private void btnDeleteAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirlineActionPerformed
        int selectedRow = tblAirlines.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airliner airline= (Airliner)tblAirlines.getValueAt(selectedRow, 0);
                this.airlineDirectory.deleteAirline(airline);
                populateTable(this.airlineDirectory.getAirlinerList());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnDeleteAirlineActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnRefreshAirlinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAirlinesActionPerformed
        // TODO add your handling code here:
        populateTable(this.airlineDirectory.getAirlinerList());
    }//GEN-LAST:event_btnRefreshAirlinesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton btnDeleteAirline;
    private javax.swing.JButton btnManageFlights;
    private javax.swing.JButton btnRefreshAirlines;
    private javax.swing.JButton btnViewAirline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirlines;
    // End of variables declaration//GEN-END:variables
}
