/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.Airplane;
import Business.Flight;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TILAK PARMAR
 */
public class ViewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightJPanel
     */
    private JPanel cardSequenceJPanel;
    private Flight flight;
    private Airliner al;
    ViewFlightJPanel(JPanel cardSequenceJPanel, Flight flight, Airliner al) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.flight = flight;
        this.al = al;
        
        comboBoxFlights.removeAllItems();
        for(Airplane a : al.getFleet().getAirplanes()) {
            comboBoxFlights.addItem(a.getModelNumber());
        }
        comboBoxFlights.setSelectedItem(flight.getAirplane().getModelNumber());
        labelHeading.setText("View " + al.getAirLinerName() + " Flight");
        
        textfieldArrivalCity.setText(flight.getArrivalCity());
        textfieldArrivalTime.setText(flight.getArrivaltime());
        textfieldDepartTime.setText(flight.getDeparturetime());
        textfieldDepartureCity.setText(flight.getDepartureCity());
        textfieldFlightDate.setText(flight.getFlyDate());
        textfieldPrice.setText(String.valueOf(flight.getPrice()));
    }
    
    private boolean DatePatternCorrect() {
       Pattern p = Pattern.compile("^[*\\d]+/[*\\d]+/[*\\d]+$");
       Matcher m = p.matcher(textfieldFlightDate.getText());
       boolean b = m.matches();
       return b;
   }
    
    private boolean DepartTimePatternCorrect() {
       Pattern p = Pattern.compile("^[*\\d]+:[*\\d]+$");
       Matcher m = p.matcher(textfieldDepartTime.getText());
       boolean b = m.matches();
       return b;
   }
    
    private boolean ArrivalTimePatternCorrect() {
       Pattern p = Pattern.compile("^[*\\d]+:[*\\d]+$");
       Matcher m = p.matcher(textfieldArrivalTime.getText());
       boolean b = m.matches();
       return b;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelHeading = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxFlights = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textfieldPrice = new javax.swing.JTextField();
        textfieldDepartTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfieldFlightDate = new javax.swing.JTextField();
        textfieldArrivalCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textfieldDepartureCity = new javax.swing.JTextField();
        textfieldArrivalTime = new javax.swing.JTextField();
        btnSaveFlight = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnUpdateFlight = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel3.setBackground(null);
        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Airplane Name:");

        jLabel4.setBackground(null);
        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("From City:");

        labelHeading.setBackground(new java.awt.Color(255, 255, 255));
        labelHeading.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeading.setText("Add a ****  Flight");

        jLabel5.setBackground(null);
        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("To City:");

        comboBoxFlights.setBackground(null);
        comboBoxFlights.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxFlights.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxFlights.setEnabled(false);
        comboBoxFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFlightsActionPerformed(evt);
            }
        });

        jLabel1.setBackground(null);
        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Price:");

        jLabel6.setBackground(null);
        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Departure Time:");

        textfieldPrice.setBackground(null);
        textfieldPrice.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldPrice.setEnabled(false);
        textfieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPriceActionPerformed(evt);
            }
        });

        textfieldDepartTime.setBackground(null);
        textfieldDepartTime.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldDepartTime.setEnabled(false);
        textfieldDepartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDepartTimeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(null);
        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("USD");

        textfieldFlightDate.setBackground(null);
        textfieldFlightDate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldFlightDate.setEnabled(false);
        textfieldFlightDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldFlightDateActionPerformed(evt);
            }
        });

        textfieldArrivalCity.setBackground(null);
        textfieldArrivalCity.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldArrivalCity.setEnabled(false);
        textfieldArrivalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldArrivalCityActionPerformed(evt);
            }
        });

        jLabel7.setBackground(null);
        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Flight Date:");

        textfieldDepartureCity.setBackground(null);
        textfieldDepartureCity.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldDepartureCity.setEnabled(false);
        textfieldDepartureCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDepartureCityActionPerformed(evt);
            }
        });

        textfieldArrivalTime.setBackground(null);
        textfieldArrivalTime.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        textfieldArrivalTime.setEnabled(false);
        textfieldArrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldArrivalTimeActionPerformed(evt);
            }
        });

        btnSaveFlight.setBackground(null);
        btnSaveFlight.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnSaveFlight.setText("Save");
        btnSaveFlight.setEnabled(false);
        btnSaveFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFlightActionPerformed(evt);
            }
        });

        jLabel8.setBackground(null);
        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Arrival Time:");

        btnUpdateFlight.setBackground(null);
        btnUpdateFlight.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnUpdateFlight.setText("Update");
        btnUpdateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFlightActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        backBtn.setText("< Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textfieldPrice))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSaveFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(textfieldArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldDepartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldArrivalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldDepartureCity, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldFlightDate, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 626, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textfieldFlightDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textfieldDepartureCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textfieldArrivalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textfieldDepartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textfieldArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textfieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateFlight)
                    .addComponent(btnSaveFlight))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFlightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxFlightsActionPerformed

    private void textfieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPriceActionPerformed

    private void textfieldDepartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDepartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDepartTimeActionPerformed

    private void textfieldFlightDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldFlightDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldFlightDateActionPerformed

    private void textfieldArrivalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldArrivalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldArrivalCityActionPerformed

    private void textfieldDepartureCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDepartureCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDepartureCityActionPerformed

    private void textfieldArrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldArrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldArrivalTimeActionPerformed

    private void btnSaveFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFlightActionPerformed
        String modelno = (String) comboBoxFlights.getSelectedItem();
        
        if(!DatePatternCorrect() || textfieldFlightDate.getText().length()!=10) {
            JOptionPane.showMessageDialog(null, "Please enter Date in MM-DD-YYYY format");
            return;
        }
        
        if(!DepartTimePatternCorrect() || textfieldDepartTime.getText().length()!=5) {
            JOptionPane.showMessageDialog(null, "Please enter Departure Time in HH:MM format");
            return;
        }
        
        if(!ArrivalTimePatternCorrect() || textfieldArrivalTime.getText().length()!=5) {
            JOptionPane.showMessageDialog(null, "Please enter Arrival Time in HH:MM format");
            return;
        }
        
        else {
            
            flight.setFlyDate(textfieldFlightDate.getText());
            flight.setArrivalCity(textfieldArrivalCity.getText());
            flight.setDepartureCity(textfieldDepartureCity.getText());
            flight.setDeparturetime(textfieldDepartTime.getText());
            flight.setArrivaltime(textfieldArrivalTime.getText());
            Airplane airplane = al.getFleet().findAirplaneByModelNumber(modelno);
            flight.setPrice(Double.parseDouble(textfieldPrice.getText()));
            flight.setAirplane(airplane);

            JOptionPane.showMessageDialog(null, "Flight Details Updated successfully for " + modelno);

            comboBoxFlights.setEnabled(false);
            textfieldArrivalCity.setEnabled(false);
            textfieldArrivalTime.setEnabled(false);
            textfieldDepartTime.setEnabled(false);
            textfieldDepartureCity.setEnabled(false);
            textfieldFlightDate.setEnabled(false);
            textfieldPrice.setEnabled(false);

            btnSaveFlight.setEnabled(false);
            btnUpdateFlight.setEnabled(true);
        }

    }//GEN-LAST:event_btnSaveFlightActionPerformed

    private void btnUpdateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFlightActionPerformed
        // TODO add your handling code here:
        
        comboBoxFlights.setEnabled(true);
        textfieldArrivalCity.setEnabled(true);
        textfieldArrivalTime.setEnabled(true);
        textfieldDepartTime.setEnabled(true);
        textfieldDepartureCity.setEnabled(true);
        textfieldFlightDate.setEnabled(true);
        textfieldPrice.setEnabled(true);
        
        btnSaveFlight.setEnabled(true);
        btnUpdateFlight.setEnabled(false);
    }//GEN-LAST:event_btnUpdateFlightActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSaveFlight;
    private javax.swing.JButton btnUpdateFlight;
    private javax.swing.JComboBox<String> comboBoxFlights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JTextField textfieldArrivalCity;
    private javax.swing.JTextField textfieldArrivalTime;
    private javax.swing.JTextField textfieldDepartTime;
    private javax.swing.JTextField textfieldDepartureCity;
    private javax.swing.JTextField textfieldFlightDate;
    private javax.swing.JTextField textfieldPrice;
    // End of variables declaration//GEN-END:variables
}
