/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.MasterFlightSchedule;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15085
 */
public class ViewAirlineJPanel extends javax.swing.JPanel {

    private JPanel cardSequenceJPanel;
    private AirlinerDirectory airlineDirectory;
    private Airliner airline;
    private MasterFlightSchedule flightSchedules;
    private String airlineName;
    public ViewAirlineJPanel(JPanel cardSequenceJPanel,Airliner airline,AirlinerDirectory airlineDirectory,MasterFlightSchedule flightSchedules) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.airlineDirectory = airlineDirectory;
        this.airline= airline;
        this.flightSchedules = flightSchedules;
        btnSave.setEnabled(false);
        txtAirlineName.setText(airline.getAirLinerName());
        this.airlineName = airline.getAirLinerName();
        populateTable(airline.getFleet().getAirplanes());
        
    }
    
    private void populateTable(ArrayList<Airplane> airplanes) {
        DefaultTableModel dtm = (DefaultTableModel) tblAirplanes.getModel();
        dtm.setRowCount(0);
        for(Airplane ap : airplanes){
            Object row[]= new Object[3];
            row[0] = ap;
            row[1] = ap.getFuelCapacity();
            row[2]=  ap.getSerialNumber();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirplanes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnViewAirplane = new javax.swing.JButton();
        btnDeleteAirplane = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        btnDeleteAirplane1 = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Airlines and Airplanes");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");

        txtAirlineName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtAirlineName.setEnabled(false);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblAirplanes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblAirplanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Number", "Fuel Capacity", "Serial Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAirplanes);
        if (tblAirplanes.getColumnModel().getColumnCount() > 0) {
            tblAirplanes.getColumnModel().getColumn(0).setResizable(false);
            tblAirplanes.getColumnModel().getColumn(1).setResizable(false);
            tblAirplanes.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Airplanes");

        btnViewAirplane.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAirplane.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnViewAirplane.setText("View an airplane");
        btnViewAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirplaneActionPerformed(evt);
            }
        });

        btnDeleteAirplane.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAirplane.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnDeleteAirplane.setText("Delete an airplane");
        btnDeleteAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirplaneActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        backBtn.setText("< Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnDeleteAirplane1.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAirplane1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnDeleteAirplane1.setText("Refresh");
        btnDeleteAirplane1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirplane1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAirlineName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(776, 896, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteAirplane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAirplane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

       txtAirlineName.setEnabled(true);
       btnSave.setEnabled(true);
       btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(txtAirlineName.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Please fill airline name");
           return;
       }
       txtAirlineName.setEnabled(false);
       btnSave.setEnabled(false);
       btnUpdate.setEnabled(true);
       this.airline.setAirLinerName(txtAirlineName.getText());
       this.flightSchedules.getFlightSchedules().put(txtAirlineName.getText(), this.flightSchedules.getFlightSchedules().get(airlineName));
       this.flightSchedules.getFlightSchedules().remove(airlineName);
       JOptionPane.showMessageDialog(null, "Airline updated successfully");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirplaneActionPerformed
        int selectedRow = tblAirplanes.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airplane airplane= (Airplane)tblAirplanes.getValueAt(selectedRow, 0);
                this.airlineDirectory.deleteAirplane(airplane,airline);
                populateTable(airline.getFleet().getAirplanes());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnDeleteAirplaneActionPerformed

    private void btnViewAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirplaneActionPerformed
        int selectedRow = tblAirplanes.getSelectedRow();
        if(selectedRow>=0){
              Airplane airplane= (Airplane)tblAirplanes.getValueAt(selectedRow, 0);
              ViewAirplaneJPanel viewJPanel = new ViewAirplaneJPanel(cardSequenceJPanel,airline,airlineDirectory,flightSchedules,airplane);
              cardSequenceJPanel.add("ViewAirplaneJPanel",viewJPanel);
              CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
              layout.next(cardSequenceJPanel);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view Details!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewAirplaneActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnDeleteAirplane1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirplane1ActionPerformed
        // TODO add your handling code here:
        populateTable(airline.getFleet().getAirplanes());
    }//GEN-LAST:event_btnDeleteAirplane1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnDeleteAirplane;
    private javax.swing.JButton btnDeleteAirplane1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirplanes;
    private javax.swing.JTextField txtAirlineName;
    // End of variables declaration//GEN-END:variables

}
